version: '3.8'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo19@2026
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql19:/var/lib/postgresql/data
    ports:
      - "5193:5432"
    command:
      - "postgres"
      - "-c"
      - "log_lock_waits=on"

  odoo19:
    image: odoo:19
    user: root
    depends_on:
      - db
    ports:
      - "19003:8069"
      - "29003:8072"
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo19@2026
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    # Install required OS packages + Python packages at container start.
    # Note: doing installs at runtime makes container start slower. See note below about building a custom image.
    command: >
      sh -c "apt-get update &&
      apt-get install -y python3-pip locales --no-install-recommends &&
      locale-gen en_US.UTF-8 &&
      pip install --no-cache-dir --break-system-packages \
        boto3 dropbox nextcloud-api-wrapper num2words openpyxl pandas \
        paramiko pyncclient pysftp translate xlrd html2text &&
      /entrypoint.sh odoo"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./enterprise19:/mnt/enterprise
      - ./etc:/etc/odoo
      - ./backup:/mnt/backup
    restart: always
